# Generated by Django 3.1 on 2025-10-21 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='descripption',
            new_name='description',
        ),
    ]
